apiVersion: v1
kind: ConfigMap
metadata:
  name: audit-log-service-config
  namespace: audit-log
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8080"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/audit"
